export const INTERESTING_PROPERTIES_GETTING = "INTERESTING_PROPERTIES_GETTING";
export const INTERESTING_PROPERTIES_GETTING_SUCCESS =
  "INTERESTING_PROPERTIES_GETTING_SUCCESS";
export const INTERESTING_PROPERTIES_GETTING_ERROR =
  "INTERESTING_PROPERTIES_GETTING_ERROR";
