export const PROPERTY_GETTING = "PROPERTY_GETTING";
export const PROPERTY_GETTING_SUCCESS = "PROPERTY_GETTING_SUCCESS";
export const PROPERTY_GETTING_ERROR = "PROPERTY_GETTING_ERROR";
export const PROPERTY_UPDATE = "PROPERTY_UPDATE";
export const PROPERTY_UPDATE_SUCCESS = "PROPERTY_UPDATE_SUCCESS";
export const PROPERTY_UPDATE_ERROR = "PROPERTY_UPDATE_ERROR";
